
BUILD_DIR := build
OUT_DIR := out
SRC_DIR := src
TMP_PREPROC_DIRNAME := tmp_preproc
HTML_FILES =
MD_FILES =
RESOURCES =
INTERMEDIATES =
.PHONY: clean all




HTML_FILES += index.html 
MD_FILES += mainpage.md blog.md
RESOURCES += trans_flag.svg styles.css
INTERMEDIATES += macros.m4 navbar.m4



PREFIXED_HTML_FILES = $(HTML_FILES:%=$(SRC_DIR)/%)
PREFIXED_MD_FILES = $(MD_FILES:%=$(SRC_DIR)/%)

TMP_PREPROC_HTML_FILES = $(HTML_FILES:%=$(BUILD_DIR)/$(TMP_PREPROC_DIRNAME)/%)
TMP_PREPROC_MD_FILES = $(MD_FILES:%.md=$(BUILD_DIR)/$(TMP_PREPROC_DIRNAME)/%.html)
TMP_PREPROC_INTERMEDIATES = $(INTERMEDIATES:%=$(BUILD_DIR)/$(TMP_PREPROC_DIRNAME)/%)

FINAL_HTML_FILES = $(HTML_FILES:%=$(BUILD_DIR)/$(OUT_DIR)/%) $(MD_FILES:%.md=$(BUILD_DIR)/$(OUT_DIR)/%.html)

FINAL_RESOURCES = $(RESOURCES:%=$(BUILD_DIR)/$(OUT_DIR)/%)

all: $(FINAL_HTML_FILES) $(FINAL_RESOURCES)

clean:
	rm -rf $(BUILD_DIR)



$(TMP_PREPROC_HTML_FILES): $(BUILD_DIR)/$(TMP_PREPROC_DIRNAME)/%: $(SRC_DIR)/% $(BUILD_DIR)/$(TMP_PREPROC_DIRNAME)
	cp $< $@

$(TMP_PREPROC_MD_FILES): $(BUILD_DIR)/$(TMP_PREPROC_DIRNAME)/%.html: $(SRC_DIR)/%.md $(BUILD_DIR)/$(TMP_PREPROC_DIRNAME)
	m4 -P -I $(dir $<) $< | pandoc --from=markdown --to=html -o $@

$(TMP_PREPROC_INTERMEDIATES): $(BUILD_DIR)/$(TMP_PREPROC_DIRNAME)/%: $(SRC_DIR)/% $(BUILD_DIR)/$(TMP_PREPROC_DIRNAME)
	cp $< $@

$(FINAL_HTML_FILES): $(BUILD_DIR)/$(OUT_DIR)/%: $(BUILD_DIR)/$(TMP_PREPROC_DIRNAME)/% $(BUILD_DIR)/$(OUT_DIR) $(FINAL_RESOURCES) $(TMP_PREPROC_INTERMEDIATES) $(TMP_PREPROC_MD_FILES) $(TMP_PREPROC_HTML_FILES)
	m4 -P -I $(dir $<) $< > $@

$(FINAL_RESOURCES): $(BUILD_DIR)/$(OUT_DIR)/%: $(SRC_DIR)/%
	cp $< $@

$(BUILD_DIR)/$(OUT_DIR):
	mkdir -p $(BUILD_DIR)/$(OUT_DIR)

$(BUILD_DIR)/$(TMP_PREPROC_DIRNAME):
	mkdir -p $(BUILD_DIR)/$(TMP_PREPROC_DIRNAME)

